- topic_name: "/clock"
  gz_type_name: "gz.msgs.Clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  direction: GZ_TO_ROS

- topic_name: "/navsat"
  gz_type_name: "ignition.msgs.NavSat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  direction: GZ_TO_ROS

- topic_name: "/imu"
  gz_type_name: "ignition.msgs.IMU"
  ros_type_name: "sensor_msgs/msg/Imu"
  direction: GZ_TO_ROS
- ros_topic_name: "/downward_camera/camera_info"
  gz_topic_name: "/camera_info"
  ros_type: "sensor_msgs/msg/CameraInfo"
  gz_type: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
